// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuGVDaBPefxhKHxG18DRRu5mnOSp-yLPY',
    appId: '1:500295967599:web:1310ac0c4f9d2be7a7fe9a',
    messagingSenderId: '500295967599',
    projectId: 'economate-app-cf49c',
    authDomain: 'economate-app-cf49c.firebaseapp.com',
    storageBucket: 'economate-app-cf49c.firebasestorage.app',
    measurementId: 'G-JHZ3MY57KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNsS3NuxNTn5cLs7WMMwHztgzUvi68Mmg',
    appId: '1:500295967599:android:baed7c8b92255d0ea7fe9a',
    messagingSenderId: '500295967599',
    projectId: 'economate-app-cf49c',
    storageBucket: 'economate-app-cf49c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4q6txUkiYqzadHQuPGVbUSJc1usTk9wM',
    appId: '1:500295967599:ios:d64aceaeae90f0f3a7fe9a',
    messagingSenderId: '500295967599',
    projectId: 'economate-app-cf49c',
    storageBucket: 'economate-app-cf49c.firebasestorage.app',
    iosBundleId: 'com.example.economateMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4q6txUkiYqzadHQuPGVbUSJc1usTk9wM',
    appId: '1:500295967599:ios:d64aceaeae90f0f3a7fe9a',
    messagingSenderId: '500295967599',
    projectId: 'economate-app-cf49c',
    storageBucket: 'economate-app-cf49c.firebasestorage.app',
    iosBundleId: 'com.example.economateMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuGVDaBPefxhKHxG18DRRu5mnOSp-yLPY',
    appId: '1:500295967599:web:ebebf03bbdbb75c5a7fe9a',
    messagingSenderId: '500295967599',
    projectId: 'economate-app-cf49c',
    authDomain: 'economate-app-cf49c.firebaseapp.com',
    storageBucket: 'economate-app-cf49c.firebasestorage.app',
    measurementId: 'G-20BC9N01Q9',
  );

}